"use client";

import { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeRaw from "rehype-raw";
import { apiFetch } from "@/lib/api";

interface Props {
  docType: string | null;
  fields: Record<string, string>;
}

const FIELD_LINK_CLASSES = new Set([
  "coverpage_link",
  "keyterms_link",
  "orderform_link",
  "businessterms_link",
  "sow_link",
]);

function normalizeKey(s: string): string {
  return s.replace(/[''′ʼ]/g, "'").trim();
}

function substituteFields(content: string, fields: Record<string, string>): string {
  const lookup: Record<string, string> = {};
  for (const [k, v] of Object.entries(fields)) {
    if (v?.trim()) lookup[normalizeKey(k)] = v.trim();
  }

  return content.replace(
    /<span class="([^"]+)">([^<]+)<\/span>/g,
    (match, cls, rawName) => {
      if (!FIELD_LINK_CLASSES.has(cls)) return match;
      const key = normalizeKey(rawName);
      const value =
        lookup[key] ??
        (key.endsWith("'s") ? lookup[key.slice(0, -2)] : undefined);
      return value
        ? `<mark class="field-filled">${value}</mark>`
        : `<em class="field-empty">[${rawName.trim()}]</em>`;
    }
  );
}

function SkeletonLoader() {
  return (
    <div className="py-6 px-4">
      <div className="bg-white rounded-xl shadow-sm max-w-3xl mx-auto p-8 animate-pulse">
        <div className="h-5 bg-gray-200 rounded w-2/3 mx-auto mb-3" />
        <div className="h-3 bg-gray-100 rounded w-1/3 mx-auto mb-8" />
        {[...Array(6)].map((_, i) => (
          <div key={i} className="mb-4 space-y-2">
            <div className="h-3 bg-gray-200 rounded w-full" />
            <div className="h-3 bg-gray-100 rounded w-5/6" />
          </div>
        ))}
      </div>
    </div>
  );
}

export default function DocumentPreview({ docType, fields }: Props) {
  const [templateContent, setTemplateContent] = useState<string | null>(null);
  const [fetchError, setFetchError] = useState<string | null>(null);

  useEffect(() => {
    if (!docType) {
      setTemplateContent(null);
      setFetchError(null);
      return;
    }
    setFetchError(null);
    setTemplateContent(null);
    apiFetch(`/api/templates/${encodeURIComponent(docType)}`)
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status} for ${docType}`);
        return r.text();
      })
      .then(setTemplateContent)
      .catch((e: Error) => setFetchError(e.message));
  }, [docType]);

  if (!docType) {
    return (
      <div className="flex flex-col items-center justify-center h-full py-16 px-8 text-center">
        <div className="w-16 h-16 rounded-2xl bg-white border border-gray-200 shadow-sm flex items-center justify-center mb-4">
          <svg className="w-8 h-8 text-gray-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5}
              d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
        </div>
        <p className="text-sm font-medium text-gray-500 mb-1">Your document will appear here</p>
        <p className="text-xs text-gray-400 max-w-xs">
          Tell the assistant what agreement you need and the preview will load instantly.
        </p>
      </div>
    );
  }

  if (fetchError) {
    return (
      <div className="py-6 px-4">
        <p className="text-sm text-red-500">Could not load template: {fetchError}</p>
      </div>
    );
  }

  if (!templateContent) {
    return <SkeletonLoader />;
  }

  const rendered = substituteFields(templateContent, fields);

  return (
    <div className="py-6 px-4 print:p-0">
      <div
        id="doc-preview"
        className="bg-white text-black font-serif text-sm leading-relaxed max-w-3xl mx-auto p-8 shadow-sm rounded-xl print:shadow-none print:rounded-none print:p-0 print:max-w-none"
      >
        <ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeRaw]}>
          {rendered}
        </ReactMarkdown>
      </div>
      <p className="text-center text-xs text-gray-400 mt-4 max-w-3xl mx-auto">
        This document is a draft generated by AI and should be considered a starting point only.
        It is not legal advice and should be reviewed by a qualified attorney before use.
      </p>
    </div>
  );
}
